### ISSUE TITLE
[3pt] Redux Create/Show Reservations

### ISSUE THREAD

**Issue by AhmadiGu** [AhmadiGu/Book-an-Appointment_back#16]
Update Redux Store:

- Define the initial state of the reservations in the store
- Update the store with newly created reservations

Add Redux Actions:

- Create an action for creating a reservation
- Create an action for updating the store with new reservations

Add Redux Reducers:

- Create a reducer for handling reservation creation
- Create a reducer for updating the store with new reservations

Unit Tests:

- Add unit tests for all the actions and reducers

**Comment by SekoViper** [comment]
Hello, how is your task going?

**Comment by AhmadiGu** [comment]
https://github.com/AhmadiGu/Book-an-Appointment_front/pull/10
